### ISSUE TITLE
Add menu item above "close tabs to the right"

### ISSUE THREAD

**Issue by Keith94** [mkopec/close-tabs-to-the-left#1]
Close tabs to the left is currently added to the bottom of the context menu. It should be inserted before "close tabs to the right" imo.

**Comment by mkopec** [comment]
I agree, however I don't think that's possible at the moment.

**Comment by vlakoff** [comment]
Refs this Mozilla ticket: [1325758 - Ability to specify insertion point for contextMenu item or submenu](https://bugzilla.mozilla.org/show_bug.cgi?id=1325758)

**Comment by hnz101** [comment]
I'm also not pleased with the default context menu order, close left/right tabs are my no.1 go-to entries.

Because unfortunately Add-On's like Menu Wizard will not work with FF57+ I am currently experimenting with userChrome.css but it seems like it is not possible to select items added by webextentions.
The following changes the Order of the default Tab-Options, but not the new entry from this extension:
`#tabContextMenu > * {-moz-box-ordinal-group:2;}`
`#close_left {-moz-box-ordinal-group:1!important;}`
`#context_closeTabsToTheEnd {-moz-box-ordinal-group:1!important;}`
`#context_undoCloseTab {-moz-box-ordinal-group:1!important;}`
`#context_closeOtherTabs {-moz-box-ordinal-group:1!important;}`

Perhaps anyone with more css experience has an Idea until (let's hope) firefox will extend it's API to deal with this mess.
